services:
  part_5:
    container_name: FIRST
    build: ./../Part_5_Dockle

  proxy:
    image: nginx:latest
    container_name: SECOND
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf 
    ports:
      - "80:8080"
    depends_on:
      - part_5
