version: '3.8'

services:
  part5:
    image: kristofs:latest
    build: ./../Part_5_Dockle
    container_name: kris
    networks:
      - local_network
    expose:
      - "81"

  image_nginx:
    image: nginx:latest
    container_name: nginx_kris
    ports:
      - "8080:80"
    networks:
      - local_network
    depends_on:
      - part5
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf 
networks:
    local_network:
      driver: bridge
